Added -t <file> option to "flash" to a custom file under Darwin version

diff --git a/Darwin/flash b/Darwin/flash
--- a/Darwin/flash
+++ b/Darwin/flash
@@ -21,6 +21,7 @@ OPTIONS:
   --device|-d     Choose device to flash to (e.g. 'disk2' for /dev/disk2)
   --userdata|-u   Copy this cloud-init file to /boot/user-data
   --metadata|-m   Copy this cloud-init file to /boot/meta-data
+  --target-file|-t   use a block file instead of a flash card (supersedes --device option)
 
 For HypriotOS devices:
 
@@ -68,6 +69,7 @@ do
     --device) args="${args}-d ";;
     --userdata) args="${args}-u ";;
     --metadata) args="${args}-m ";;
+    --target-file) args="${args}-t ";;
     # pass through anything else
     *) [[ "${arg:0:1}" == "-" ]] || delim="\""
       args="${args}${delim}${arg}${delim} ";;
@@ -76,7 +78,7 @@ done
 # reset the translated args
 eval set -- "$args"
 # now we can process with getopt
-while getopts ":hc:n:s:p:C:l:d:u:m:" opt; do
+while getopts ":hc:n:s:p:C:l:d:u:m:t:" opt; do
   case $opt in
     h)  usage ;;
     c)  CONFIG_FILE=$OPTARG ;;
@@ -88,6 +90,7 @@ while getopts ":hc:n:s:p:C:l:d:u:m:" opt; do
     d)  DEVICE=$OPTARG ;;
     u)  USER_DATA=$OPTARG ;;
     m)  META_DATA=$OPTARG ;;
+    t)  TARGET_FILE=$OPTARG ;;
     \?) usage ;;
     :)
       echo "option -$OPTARG requires an argument"
@@ -191,54 +194,71 @@ if [[ "${OSTYPE}" != "darwin"* ]]; then
   exit 11
 fi
 
-while true; do
-  # default to device passed by user
-  disk="$DEVICE"
-  if [ "${disk}" == "" ]; then
-    # try to find the correct disk of the inserted SD card
-    disk=$(diskutil list | grep --color=never FDisk_partition_scheme | awk 'NF>1{print $NF}')
+if [ ! -z "${TARGET_FILE}" ]; then
+  if [ -e "${TARGET_FILE}" ] && [ ! -f "${TARGET_FILE}" ]; then
+    echo "File ${TARGET_FILE} exists and is not a regular file"
+    exit 12
   fi
-  if [ "${disk}" == "" ]; then
-    echo "No SD card found. Please insert SD card, I'll wait for it..."
-    while [ "${disk}" == "" ]; do
-      sleep 1
-      disk=$(diskutil list | grep --color=never FDisk_partition_scheme | awk 'NF>1{print $NF}')
-    done
+  cp ${image} ${TARGET_FILE}
+  if [ $? -ne 0 ]; then
+    echo "Cannot create target block file ${TARGET_FILE}"
+    exit 12
   fi
+  dev_disk=$(hdiutil attach "${TARGET_FILE}" | grep --color=never FDisk_partition_scheme 2>&1 | awk '{print $1}')
+  disk=$(basename ${dev_disk})
+  DEVICE=${disk}
 
-  df -h
+else
   while true; do
-    echo ""
-    read -rp "Is /dev/${disk} correct? " yn
-    case $yn in
-      [Yy]* ) break;;
-      [Nn]* ) exit;;
-      * ) echo "Please answer yes or no.";;
-    esac
+    # default to device passed by user
+    disk="$DEVICE"
+    if [ "${disk}" == "" ]; then
+      # try to find the correct disk of the inserted SD card
+      disk=$(diskutil list | grep --color=never FDisk_partition_scheme | awk 'NF>1{print $NF}')
+    fi
+    if [ "${disk}" == "" ]; then
+      echo "No SD card found. Please insert SD card, I'll wait for it..."
+      while [ "${disk}" == "" ]; do
+        sleep 1
+        disk=$(diskutil list | grep --color=never FDisk_partition_scheme | awk 'NF>1{print $NF}')
+      done
+    fi
+
+    df -h
+    while true; do
+      echo ""
+      read -rp "Is /dev/${disk} correct? " yn
+      case $yn in
+        [Yy]* ) break;;
+        [Nn]* ) exit;;
+        * ) echo "Please answer yes or no.";;
+      esac
+    done
+
+    echo "Unmounting ${disk} ..."
+    diskutil unmountDisk "/dev/${disk}s1"
+    diskutil unmountDisk "/dev/${disk}"
+    readonlymedia=$(diskutil info "/dev/${disk}" | grep "Read-Only Media" | awk 'NF>1{print $NF}')
+    if [ "$readonlymedia" == "No" ]; then
+      break
+    else
+      afplay /System/Library/Sounds/Basso.aiff
+      echo "👎  The SD card is write protected. Please eject, remove protection and insert again."
+    fi
   done
 
-  echo "Unmounting ${disk} ..."
-  diskutil unmountDisk "/dev/${disk}s1"
-  diskutil unmountDisk "/dev/${disk}"
-  readonlymedia=$(diskutil info "/dev/${disk}" | grep "Read-Only Media" | awk 'NF>1{print $NF}')
-  if [ "$readonlymedia" == "No" ]; then
-    break
+  echo "Flashing ${image} to ${disk} ..."
+  if [[ -x $(which pv) ]]; then
+    # this sudo here is used for a login without pv's progress bar
+    # hiding the password prompt
+    size=$(sudo /usr/bin/stat -f %z ${image})
+    pv -s "${size}" < ${image} | sudo /bin/dd bs=1m "of=/dev/r${disk}"
   else
-    afplay /System/Library/Sounds/Basso.aiff
-    echo "👎  The SD card is write protected. Please eject, remove protection and insert again."
+    echo "No 'pv' command found, so no progress available."
+    echo "Press CTRL+T if you want to see the current info of dd command."
+    sudo /bin/dd bs=1m if=${image} "of=/dev/r${disk}"
   fi
-done
 
-echo "Flashing ${image} to ${disk} ..."
-if [[ -x $(which pv) ]]; then
-  # this sudo here is used for a login without pv's progress bar
-  # hiding the password prompt
-  size=$(sudo /usr/bin/stat -f %z ${image})
-  pv -s "${size}" < ${image} | sudo /bin/dd bs=1m "of=/dev/r${disk}"
-else
-  echo "No 'pv' command found, so no progress available."
-  echo "Press CTRL+T if you want to see the current info of dd command."
-  sudo /bin/dd bs=1m if=${image} "of=/dev/r${disk}"
 fi
 
 boot=$(df | grep --color=never "/dev/${disk}s1" | /usr/bin/sed 's,.*/Volumes,/Volumes,')
